global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-app:8080']
        labels:
          app: 'order-service'
          env: 'dev'
